# Generated by Django 4.1 on 2022-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(default="", max_length=150),
        ),
    ]
