# Generated by Django 4.1 on 2022-09-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_room_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name_plural": "Amenities"},
        ),
        migrations.RenameField(
            model_name="room",
            old_name="pet_friendlt",
            new_name="pet_friendly",
        ),
    ]
