# Generated by Django 4.1 on 2022-09-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="experince",
            new_name="experience",
        ),
    ]
